#!/usr/bin/env bash

[ "${TALEND_BUILD_FLAG:-0}" -gt 0 ] && return 0

export TALEND_BUILD_FLAG=1

set -e
set -u
set -o pipefail

talend_build_script_path=$(readlink -e "${BASH_SOURCE[0]}")
talend_build_script_dir="${talend_build_script_path%/*}"

source "${talend_build_script_dir}/../util/util.sh"

export INFO_LOG=true
#export DEBUG_LOG=true

if [ "${1:-}" == "-h" ]; then
    declare usage="./build <client_name> <project_name> <job_name> <job_version> <job_tgz_file> [ <job_parent_id> ]"
    echo "${usage}"
    exit
fi

declare -r client_name="${1:-}"
declare -r project_name="${2:-}"
declare -r job_name="${3:-}"
declare -r job_version="${4:-}"
declare -r job_tgz_file="${5:-}"
declare -r job_parent_dir="${6:-/talend}"

declare -r client_name_toLower=$(echo "${client_name}" | awk '{print tolower($0)}')
declare -r project_name_toLower=$(echo "${project_name}" | awk '{print tolower($0)}')
declare -r job_name_toLower=$(echo "${job_name}" | awk '{print tolower($0)}')

required client_name project_name job_name job_version job_tgz_file job_parent_dir

declare -r image_tag="${client_name_toLower}/${project_name_toLower}/${job_name_toLower}:${job_version}"

infoVar client_name 
infoVar project_name
infoVar job_name
infoVar job_version
infoVar job_tgz_file
infoVar job_parent_dir
infoVar image_tag

pushd "${talend_build_script_dir}"

cp "${job_tgz_file}" job.tgz

cp Dockerfile.template Dockerfile

cat >> Dockerfile << EOF
ENTRYPOINT [ "/bin/ash", "${job_parent_dir}/${job_name}_${job_version}/${job_name}/${job_name}_run.sh" ]
EOF

debugLog docker build --no-cache -t "${image_tag}" \
                      --build-arg job_name="${job_name}" \
                      --build-arg job_version="${job_version}" \
                      --build-arg job_tgz_file="job.tgz" \
                      --build-arg job_parent_dir="${job_parent_dir}" .

docker build --no-cache -t "${image_tag}" \
             --build-arg job_name="${job_name}" \
             --build-arg job_version="${job_version}" \
             --build-arg job_tgz_file="job.tgz" \
             --build-arg job_parent_dir="${job_parent_dir}" .

rm job.tgz

popd

infoLog "Finished"
